execute pathogen#infect()

" Learn vim, damnit!
nnoremap <Left> :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up> :echoe "Use k"<CR>
nnoremap <Down> :echoe "Use j"<CR>

" When the terminal supports colors, switch syntax highlighting on.
if (&t_Co > 2 || has("gui_running")) && !exists("syntax_on")
    syntax on
endif

" Speed Improvements
set lazyredraw
set ttyfast

" Misc. Config
set nocompatible
set autowrite
set splitbelow
set splitright
set number
set list listchars=tab:»·,trail:·
au FocusLost * :wa

" Misc. Mappings
noremap <Tab> ^==<Esc>

" CtrlP
let g:ctrlp_custom_ignore = {
    \ 'dir':  '\v[\/](\.(git|hg|svn)|\_site)$',
    \ 'file': '\v\.(exe|so|dll|class|png|jpg|jpeg)$',
    \}
let g:ctrlp_working_path_mode = 'r'
nmap <leader>p :CtrlP<CR>
nmap <leader>bb :CtrlPBuffer<CR>
nmap <leader>bm :CtrlPMixed<CR>
nmap <leader>bs :CtrlPMRU<CR>

" Buffergator
set hidden
let g:buffergator_viewport_split_policy = 'R'
let g:buffergator_suppress_keymaps = 1
nmap <leader>jj :BuffergatorMruCyclePrev<CR>
nmap <leader>kk :BuffergatorMruCycleNext<CR>
nmap <leader>bl :BuffergatorOpen<CR>
nmap <leader>T :enew<CR>
nmap <leader>bq :bp <BAR> bd #<CR>

" Leader Mappings
map <Space> <leader>
map <leader>w :update<CR>
map <leader>q :qall<CR>

" Various useful keybindings
" Search word under cursor
nnoremap K :Ag "\b<C-R><C-W>\b"<CR>:cw<CR> 

" Color Scheme
colorscheme solarized
set background=dark
set encoding=utf-8

" Airline Config
set noshowmode
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline#extensions#tabline#enabled = 1
let g:airline_symbols.space = "\ua0"
let g:airline_theme='solarized'
set t_Co=256

" Indentation
set tabstop=4
set shiftwidth=4
set expandtab

" Indentation in Python
au FileType py set autoindent
au FileType py set smartindent
au FileType py set textwidth=79

" jedi-vim
let g:jedi#show_call_signatures = "2"

" Use The Silver Searcher https://github.com/ggreer/the_silver_searcher
if executable('ag')
    set grepprg=ag\ --nogroup
    let g:grep_cmd_opts = '--line-numbers --noheading'
    let g:ctrlp_user_command = 'ag %s -l -g ""'
    let g:ctrlp_use_caching = 0
endif

" ag.vim
let g:ag_working_path_mode="r"

" cmd n, cmd p for fwd/backward in search
map <C-n> :cn<CR>
map <C-p> :cp<CR>

" Easy navigation between splits. Instead of ctrl-w + j. Just ctrl-j
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>"
