#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Ben O'Hara <bohara@gmail.com>
#

# Customize to your needs...

alias pwp="cd ~/Projects/DUO/pathwright_provisioning/pathwright"
alias flushdns="sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder"

ppcat() {
    local out colored
    out=$(/bin/cat $@)
    colored=$(echo $out | pygmentize -f console -g 2>/dev/null)
    [[ -n $colored ]] && echo "$colored" || echo "$out"
}

# Setting PATH for Python 3.5
# The orginal version is saved in .zprofile.pysave
# PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"
# export PATH

eval $(/opt/homebrew/bin/brew shellenv)
