#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Defines environment variables.
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

# Dont read global configs
unsetopt GLOBAL_RCS

# Set the path to oh-my-zsh.
export ZSH="$HOME/.oh-my-zsh"

eval `/usr/libexec/path_helper -s`

export PATH=$HOME/bin:$HOME/.dotfiles/dotsync/bin:/usr/local/bin:$PATH

# Customize to your needs...

export DSHOST="`hostname -s`.local"

# zsh handles this
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export WORKON_HOME=~/.venv
export PROJECT_HOME=~/Projects/Personal

export PAGER="less"
export EDITOR="vim"
export VISUAL="vim"

export DISABLE_AUTO_TITLE=true

#export KUBECONFIG=/Users/bradreardon/Projects/DUO/pathwright_provisioning/kubernetes/kubeconfig
#eval "$(pyenv init -)"
#pyenv virtualenvwrapper_lazy

export GITHUB_USERNAME=bradreardon
export PW_PROVISIONING_DIR=/Users/bradreardon/Projects/DUO/pathwright_provisioning
export DOCKER_BUILDKIT=1
