#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Defines environment variables.
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

# Dont read global configs
unsetopt GLOBAL_RCS

# Set the path to oh-my-zsh.
export ZSH="$HOME/.oh-my-zsh"

eval `/usr/libexec/path_helper -s`

export PATH=$HOME/bin:$HOME/.dotfiles/dotsync/bin:/usr/local/bin:$PATH

# Customize to your needs...

export DSHOST="`hostname -s`.local"

export WORKON_HOME=~/.virtualenvs
export ANSIBLE_CONFIG=~/.ansible.cfg
