#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Sets dotzsh options.
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

DISABLE_AUTO_UPDATE="true"

ZSH_THEME="agnoster"

plugins=(git adb bower brew common-aliases command-not-found cp django gitignore history osx pip python sudo vagrant zsh_reload)

DEFAULT_USER="bradreardon"

### Load oh-my-zsh
source "$ZSH/oh-my-zsh.sh"

### Customize to your needs...

